name: 'Terraform Apply on Merge'

on:
  pull_request:
    types: [closed]
    

jobs:
  terraform:
    name: 'Terraform Apply on PR'
    runs-on: ubuntu-latest
    env:
        PAT: # update personal access token here for apply comments on PR ${{ secrets.TOKEN_GITHUB }}
    defaults:
      run:
        shell: bash

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Branch name
      id: branch
      run: echo "BRANCH=$(echo ${GITHUB_HEAD_REF##*/})" >> $GITHUB_ENV}

    - name: Configure AWS Credentials - US-DEV
      if: ${{ steps.branch.outputs }} == 'us-dev'
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: #Update aws credentials for terraform ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: #Update aws credentials for terraform ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    - name: Setup Terragrunt
      uses: autero1/action-terragrunt@v1.1.1
      with:
        terragrunt_version: latest

    - name: Terragrunt Version
      run: terragrunt --version
 
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      
    - name: Terraform Init
      run: terragrunt run-all init
      
    - name: Terraform Plan
      id: plan
      run: terragrunt run-all plan

    - name: Post Plan
      uses: robburger/terraform-pr-commenter@v1
      env:
          GITHUB_TOKEN: ${{ secrets.TOKEN_GITHUB }}
      with:
        commenter_type: plan
        commenter_input: ${{ format('{0}{1}', steps.plan.outputs.stdout, steps.plan.outputs.stderr) }}
        commenter_exitcode: ${{ steps.plan.outputs.exitcode }}

    - name: Terraform Apply
      id: apply
      run: terragrunt run-all apply --terragrunt-non-interactive
